import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
    <script src="https://kit.fontawesome.com/5eed2da627.js" crossorigin="anonymous" defer></script>

    </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
